### PR TITLE
Better dependencies checker by notifying user if not satisfied.

### LINKED ISSUE #20: Notify user if dependencies are not met
Currently it doesn't display anything if Booking is not active and it informs the user the plugin is successfully activated.

### LINKED ISSUE #21: Added PHP 5.3 as dependency
In #19 we added `DateTime::createFromFormat` that's available in >= PHP 5.3.

### PR DESCRIPTION
**Pull request by gedex**
Resolves #20. Also resolves #21.

### CODE REVIEW

**Comment by gedex** [comment]
@roykho Please review.

**Comment by gedex** [comment]
@roykho Code updated. Please verify again.

**Comment by gedex** [comment]
@roykho That's expected. Only happens in plugin activation.

**Comment by roykho** [comment]
Yes I understand however that is not very graceful notice.  It should look more like this

**Comment by gedex** [comment]
@roykho I've removed `trigger_error`, please verify again.

**Comment by gedex** [comment]
@dwainm Could you please review this when have a moment? Planning to release after merging this one.

**Comment by dwainm** [comment]
@gedex getting fatal error: 

Fatal error: Class 'WC_Product_Booking' not found in /srv/www/wordpress-trunk/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-product-accommodation-booking.php on line 10

**Comment by dwainm** [comment]
The fatal error occurs on this branch after deactivating Bookings.

**Comment by gedex** [comment]
Great finding @dwainm! Apparently `woocommerce_loaded` is fired before `plugins_loaded`. In https://github.com/woothemes/woocommerce-accommodation-bookings/commit/0e65891d90569ade4b475bad80d487830036492f, I also check dependencies in `includes` method. Also, refactor the checker a bit to cache check result. Please verify again.

**Comment by dwainm** [comment]
@gedex getting this now:

Fatal error: Call to undefined function deactivate_plugins() in /srv/www/wordpress-trunk/wp-content/plugins/woocommerce-accommodation-bookings/includes/class-wc-accommodation-bookings-plugin.php on line 98

**Comment by gedex** [comment]
It's weird that I couldn't get `undefined function deactivate_plugins()` error. However, I check function existence on that in https://github.com/woothemes/woocommerce-accommodation-bookings/commit/ed7fa04761fd01b3b87e1fc80b727f47008f9450. Also checking is moved into the constructor so hooks are not registered if dependencies are not satisfied. Sorry to ask again, could please verify again :)

**Comment by dwainm** [comment]
perfect @gedex  :)

**Comment by gedex** [comment]
Ah finally :smile:. Thanks @dwainm !

**Pull request merged**
